// Code generated by core/vm/gen; DO NOT EDIT.

package vm

import (
	"fmt"

	"github.com/ethereum/go-ethereum/common/math"
	"github.com/ethereum/go-ethereum/core/tracing"
)

// execUntraced is the generated, tracing-free interpreter fast path. Hot,
// fork-stable opcodes are inlined with their static gas and stack bounds emitted
// as constants. Fork-invariant ops (KECCAK256/MLOAD/MSTORE/MSTORE8) call their
// handler and gas functions directly by name. Everything fork-varying is
// dispatched through the active per-fork table in the default case. EVM.Run
// selects this path when no tracer is configured.
func (evm *EVM) execUntraced(scope *ScopeContext) (ret []byte, err error) {
	var (
		contract  = scope.Contract
		mem       = scope.Memory
		stack     = scope.Stack
		table     = evm.table
		rules     = evm.chainRules
		isEIP4762 = rules.IsEIP4762
		pc        = uint64(0)
		res       []byte
	)
	// Which of these the switch uses depends on the tier assignments, so
	// keep them all live rather than tracking usage while emitting.
	_, _, _, _ = mem, rules, isEIP4762, table
mainLoop:
	for {
		if isEIP4762 && !contract.IsDeployment && !contract.IsSystemCall {
			contractAddr := contract.Address()
			consumed, wanted := evm.TxContext.AccessEvents.CodeChunksRangeGas(contractAddr, pc, 1, uint64(len(contract.Code)), false, contract.Gas.ExecutionGas)
			contract.chargeExecution(consumed, evm.Config.Tracer, tracing.GasChangeWitnessCodeChunk)
			if consumed < wanted {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
		}

		op := contract.GetOp(pc)
		switch op {
		case ADD:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			y.Add(x, y)
			pc++
			continue mainLoop

		case MUL:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5
			contract.Gas.UsedExecutionGas += 5

			x, y := scope.Stack.pop1Peek1()
			y.Mul(x, y)
			pc++
			continue mainLoop

		case SUB:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			y.Sub(x, y)
			pc++
			continue mainLoop

		case DIV:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5
			contract.Gas.UsedExecutionGas += 5

			x, y := scope.Stack.pop1Peek1()
			y.Div(x, y)
			pc++
			continue mainLoop

		case SDIV:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5
			contract.Gas.UsedExecutionGas += 5

			x, y := scope.Stack.pop1Peek1()
			y.SDiv(x, y)
			pc++
			continue mainLoop

		case MOD:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5
			contract.Gas.UsedExecutionGas += 5

			x, y := scope.Stack.pop1Peek1()
			y.Mod(x, y)
			pc++
			continue mainLoop

		case SMOD:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5
			contract.Gas.UsedExecutionGas += 5

			x, y := scope.Stack.pop1Peek1()
			y.SMod(x, y)
			pc++
			continue mainLoop

		case ADDMOD:
			if stack.len() < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 3}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 8 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 8
			contract.Gas.UsedExecutionGas += 8

			x, y, z := scope.Stack.pop2Peek1()
			z.AddMod(x, y, z)
			pc++
			continue mainLoop

		case MULMOD:
			if stack.len() < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 3}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 8 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 8
			contract.Gas.UsedExecutionGas += 8

			x, y, z := scope.Stack.pop2Peek1()
			z.MulMod(x, y, z)
			pc++
			continue mainLoop

		case SIGNEXTEND:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5
			contract.Gas.UsedExecutionGas += 5

			back, num := scope.Stack.pop1Peek1()
			num.ExtendSign(num, back)
			pc++
			continue mainLoop

		case LT:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			if x.Lt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case GT:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			if x.Gt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case SLT:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			if x.Slt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case SGT:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			if x.Sgt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case EQ:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			if x.Eq(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case ISZERO:
			if stack.len() < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x := scope.Stack.peek()
			if x.IsZero() {
				x.SetOne()
			} else {
				x.Clear()
			}
			pc++
			continue mainLoop

		case AND:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			y.And(x, y)
			pc++
			continue mainLoop

		case OR:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			y.Or(x, y)
			pc++
			continue mainLoop

		case XOR:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x, y := scope.Stack.pop1Peek1()
			y.Xor(x, y)
			pc++
			continue mainLoop

		case NOT:
			if stack.len() < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			x := scope.Stack.peek()
			x.Not(x)
			pc++
			continue mainLoop

		case BYTE:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			th, val := scope.Stack.pop1Peek1()
			val.Byte(th)
			pc++
			continue mainLoop

		case SHL:
			if rules.IsConstantinople {
				if stack.len() < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 3 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 3
				contract.Gas.UsedExecutionGas += 3

				shift, value := scope.Stack.pop1Peek1()
				if shift.LtUint64(256) {
					value.Lsh(value, uint(shift.Uint64()))
				} else {
					value.Clear()
				}
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SHR:
			if rules.IsConstantinople {
				if stack.len() < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 3 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 3
				contract.Gas.UsedExecutionGas += 3

				shift, value := scope.Stack.pop1Peek1()
				if shift.LtUint64(256) {
					value.Rsh(value, uint(shift.Uint64()))
				} else {
					value.Clear()
				}
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SAR:
			if rules.IsConstantinople {
				if stack.len() < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 3 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 3
				contract.Gas.UsedExecutionGas += 3

				shift, value := scope.Stack.pop1Peek1()
				if shift.GtUint64(256) {
					if value.Sign() >= 0 {
						value.Clear()
					} else {

						value.SetAllOne()
					}
					pc++
					continue mainLoop
				}
				n := uint(shift.Uint64())
				value.SRsh(value, n)
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case CLZ:
			if rules.IsOsaka {
				if stack.len() < 1 {
					res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 5 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 5
				contract.Gas.UsedExecutionGas += 5

				x := scope.Stack.peek()
				x.SetUint64(256 - uint64(x.BitLen()))
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case KECCAK256:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 30 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 30
			contract.Gas.UsedExecutionGas += 30

			var memorySize uint64
			memSize, overflow := memoryKeccak256(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := gasKeccak256(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opKeccak256(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case POP:
			if stack.len() < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 2 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 2
			contract.Gas.UsedExecutionGas += 2

			scope.Stack.drop()
			pc++
			continue mainLoop

		case MLOAD:
			if stack.len() < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			var memorySize uint64
			memSize, overflow := memoryMLoad(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := pureMemoryGascost(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMload(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			var memorySize uint64
			memSize, overflow := memoryMStore(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := pureMemoryGascost(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE8:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			var memorySize uint64
			memSize, overflow := memoryMStore8(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := pureMemoryGascost(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore8(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case JUMP:
			if stack.len() < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 8 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 8
			contract.Gas.UsedExecutionGas += 8

			if evm.abort.Load() {
				res, err = nil, errStopToken
				break mainLoop
			}
			pos := scope.Stack.pop1()
			if !contract.validJumpdest(pos) {
				res, err = nil, ErrInvalidJump
				break mainLoop
			}
			pc = pos.Uint64() - 1
			pc++
			continue mainLoop

		case JUMPI:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 10 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 10
			contract.Gas.UsedExecutionGas += 10

			if evm.abort.Load() {
				res, err = nil, errStopToken
				break mainLoop
			}
			pos, cond := scope.Stack.pop2()
			if !cond.IsZero() {
				if !contract.validJumpdest(pos) {
					res, err = nil, ErrInvalidJump
					break mainLoop
				}
				pc = pos.Uint64() - 1
			}
			pc++
			continue mainLoop

		case PC:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 2 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 2
			contract.Gas.UsedExecutionGas += 2

			elem := scope.Stack.get()
			elem.SetUint64(pc)
			pc++
			continue mainLoop

		case MSIZE:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 2 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 2
			contract.Gas.UsedExecutionGas += 2

			elem := scope.Stack.get()
			elem.SetUint64(uint64(scope.Memory.Len()))
			pc++
			continue mainLoop

		case JUMPDEST:
			if contract.Gas.ExecutionGas < 1 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 1
			contract.Gas.UsedExecutionGas += 1

			pc++
			continue mainLoop

		case PUSH0:
			if rules.IsShanghai {
				if stack.len() > 1023 {
					res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 2 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 2
				contract.Gas.UsedExecutionGas += 2

				elem := scope.Stack.get()
				elem.Clear()
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case PUSH1:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			codeLen := uint64(len(contract.Code))
			elem := scope.Stack.get()
			pc += 1
			if pc < codeLen {
				elem.SetUint64(uint64(contract.Code[pc]))
			} else {
				elem.Clear()
			}
			pc++
			continue mainLoop

		case PUSH2:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			codeLen := uint64(len(contract.Code))
			elem := scope.Stack.get()
			if pc+2 < codeLen {
				elem.SetBytes2(contract.Code[pc+1 : pc+3])
			} else if pc+1 < codeLen {
				elem.SetUint64(uint64(contract.Code[pc+1]) << 8)
			} else {
				elem.Clear()
			}
			pc += 2
			pc++
			continue mainLoop

		case PUSH3:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+3)
			)
			elem := scope.Stack.get()
			if end-start == 3 {
				elem.SetBytes3(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 3 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 3
			pc++
			continue mainLoop

		case PUSH4:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+4)
			)
			elem := scope.Stack.get()
			if end-start == 4 {
				elem.SetBytes4(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 4 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 4
			pc++
			continue mainLoop

		case PUSH5:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+5)
			)
			elem := scope.Stack.get()
			if end-start == 5 {
				elem.SetBytes5(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 5 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 5
			pc++
			continue mainLoop

		case PUSH6:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+6)
			)
			elem := scope.Stack.get()
			if end-start == 6 {
				elem.SetBytes6(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 6 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 6
			pc++
			continue mainLoop

		case PUSH7:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+7)
			)
			elem := scope.Stack.get()
			if end-start == 7 {
				elem.SetBytes7(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 7 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 7
			pc++
			continue mainLoop

		case PUSH8:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+8)
			)
			elem := scope.Stack.get()
			if end-start == 8 {
				elem.SetBytes8(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 8 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 8
			pc++
			continue mainLoop

		case PUSH9:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+9)
			)
			elem := scope.Stack.get()
			if end-start == 9 {
				elem.SetBytes9(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 9 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 9
			pc++
			continue mainLoop

		case PUSH10:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+10)
			)
			elem := scope.Stack.get()
			if end-start == 10 {
				elem.SetBytes10(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 10 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 10
			pc++
			continue mainLoop

		case PUSH11:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+11)
			)
			elem := scope.Stack.get()
			if end-start == 11 {
				elem.SetBytes11(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 11 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 11
			pc++
			continue mainLoop

		case PUSH12:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+12)
			)
			elem := scope.Stack.get()
			if end-start == 12 {
				elem.SetBytes12(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 12 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 12
			pc++
			continue mainLoop

		case PUSH13:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+13)
			)
			elem := scope.Stack.get()
			if end-start == 13 {
				elem.SetBytes13(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 13 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 13
			pc++
			continue mainLoop

		case PUSH14:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+14)
			)
			elem := scope.Stack.get()
			if end-start == 14 {
				elem.SetBytes14(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 14 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 14
			pc++
			continue mainLoop

		case PUSH15:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+15)
			)
			elem := scope.Stack.get()
			if end-start == 15 {
				elem.SetBytes15(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 15 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 15
			pc++
			continue mainLoop

		case PUSH16:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+16)
			)
			elem := scope.Stack.get()
			if end-start == 16 {
				elem.SetBytes16(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 16 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 16
			pc++
			continue mainLoop

		case PUSH17:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+17)
			)
			elem := scope.Stack.get()
			if end-start == 17 {
				elem.SetBytes17(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 17 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 17
			pc++
			continue mainLoop

		case PUSH18:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+18)
			)
			elem := scope.Stack.get()
			if end-start == 18 {
				elem.SetBytes18(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 18 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 18
			pc++
			continue mainLoop

		case PUSH19:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+19)
			)
			elem := scope.Stack.get()
			if end-start == 19 {
				elem.SetBytes19(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 19 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 19
			pc++
			continue mainLoop

		case PUSH20:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+20)
			)
			elem := scope.Stack.get()
			if end-start == 20 {
				elem.SetBytes20(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 20 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 20
			pc++
			continue mainLoop

		case PUSH21:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+21)
			)
			elem := scope.Stack.get()
			if end-start == 21 {
				elem.SetBytes21(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 21 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 21
			pc++
			continue mainLoop

		case PUSH22:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+22)
			)
			elem := scope.Stack.get()
			if end-start == 22 {
				elem.SetBytes22(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 22 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 22
			pc++
			continue mainLoop

		case PUSH23:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+23)
			)
			elem := scope.Stack.get()
			if end-start == 23 {
				elem.SetBytes23(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 23 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 23
			pc++
			continue mainLoop

		case PUSH24:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+24)
			)
			elem := scope.Stack.get()
			if end-start == 24 {
				elem.SetBytes24(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 24 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 24
			pc++
			continue mainLoop

		case PUSH25:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+25)
			)
			elem := scope.Stack.get()
			if end-start == 25 {
				elem.SetBytes25(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 25 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 25
			pc++
			continue mainLoop

		case PUSH26:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+26)
			)
			elem := scope.Stack.get()
			if end-start == 26 {
				elem.SetBytes26(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 26 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 26
			pc++
			continue mainLoop

		case PUSH27:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+27)
			)
			elem := scope.Stack.get()
			if end-start == 27 {
				elem.SetBytes27(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 27 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 27
			pc++
			continue mainLoop

		case PUSH28:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+28)
			)
			elem := scope.Stack.get()
			if end-start == 28 {
				elem.SetBytes28(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 28 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 28
			pc++
			continue mainLoop

		case PUSH29:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+29)
			)
			elem := scope.Stack.get()
			if end-start == 29 {
				elem.SetBytes29(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 29 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 29
			pc++
			continue mainLoop

		case PUSH30:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+30)
			)
			elem := scope.Stack.get()
			if end-start == 30 {
				elem.SetBytes30(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 30 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 30
			pc++
			continue mainLoop

		case PUSH31:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+31)
			)
			elem := scope.Stack.get()
			if end-start == 31 {
				elem.SetBytes31(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 31 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 31
			pc++
			continue mainLoop

		case PUSH32:
			if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+32)
			)
			elem := scope.Stack.get()
			if end-start == 32 {
				elem.SetBytes32(contract.Code[start:end])
			} else {
				elem.SetBytes(contract.Code[start:end])

				if missing := 32 - (end - start); missing > 0 {
					elem.Lsh(elem, uint(8*missing))
				}
			}
			pc += 32
			pc++
			continue mainLoop

		case DUP1:
			if stack.len() < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 1}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(1)
			pc++
			continue mainLoop

		case DUP2:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(2)
			pc++
			continue mainLoop

		case DUP3:
			if stack.len() < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 3}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(3)
			pc++
			continue mainLoop

		case DUP4:
			if stack.len() < 4 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 4}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(4)
			pc++
			continue mainLoop

		case DUP5:
			if stack.len() < 5 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 5}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(5)
			pc++
			continue mainLoop

		case DUP6:
			if stack.len() < 6 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 6}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(6)
			pc++
			continue mainLoop

		case DUP7:
			if stack.len() < 7 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 7}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(7)
			pc++
			continue mainLoop

		case DUP8:
			if stack.len() < 8 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 8}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(8)
			pc++
			continue mainLoop

		case DUP9:
			if stack.len() < 9 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 9}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(9)
			pc++
			continue mainLoop

		case DUP10:
			if stack.len() < 10 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 10}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(10)
			pc++
			continue mainLoop

		case DUP11:
			if stack.len() < 11 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 11}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(11)
			pc++
			continue mainLoop

		case DUP12:
			if stack.len() < 12 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 12}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(12)
			pc++
			continue mainLoop

		case DUP13:
			if stack.len() < 13 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 13}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(13)
			pc++
			continue mainLoop

		case DUP14:
			if stack.len() < 14 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 14}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(14)
			pc++
			continue mainLoop

		case DUP15:
			if stack.len() < 15 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 15}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(15)
			pc++
			continue mainLoop

		case DUP16:
			if stack.len() < 16 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 16}
				break mainLoop
			} else if stack.len() > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.dup(16)
			pc++
			continue mainLoop

		case SWAP1:
			if stack.len() < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap1()
			pc++
			continue mainLoop

		case SWAP2:
			if stack.len() < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 3}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap2()
			pc++
			continue mainLoop

		case SWAP3:
			if stack.len() < 4 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 4}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap3()
			pc++
			continue mainLoop

		case SWAP4:
			if stack.len() < 5 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 5}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap4()
			pc++
			continue mainLoop

		case SWAP5:
			if stack.len() < 6 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 6}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap5()
			pc++
			continue mainLoop

		case SWAP6:
			if stack.len() < 7 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 7}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap6()
			pc++
			continue mainLoop

		case SWAP7:
			if stack.len() < 8 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 8}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap7()
			pc++
			continue mainLoop

		case SWAP8:
			if stack.len() < 9 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 9}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap8()
			pc++
			continue mainLoop

		case SWAP9:
			if stack.len() < 10 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 10}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap9()
			pc++
			continue mainLoop

		case SWAP10:
			if stack.len() < 11 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 11}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap10()
			pc++
			continue mainLoop

		case SWAP11:
			if stack.len() < 12 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 12}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap11()
			pc++
			continue mainLoop

		case SWAP12:
			if stack.len() < 13 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 13}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap12()
			pc++
			continue mainLoop

		case SWAP13:
			if stack.len() < 14 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 14}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap13()
			pc++
			continue mainLoop

		case SWAP14:
			if stack.len() < 15 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 15}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap14()
			pc++
			continue mainLoop

		case SWAP15:
			if stack.len() < 16 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 16}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap15()
			pc++
			continue mainLoop

		case SWAP16:
			if stack.len() < 17 {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: 17}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3
			contract.Gas.UsedExecutionGas += 3

			scope.Stack.swap16()
			pc++
			continue mainLoop

		default:
			operation := table[op]
			if stack.len() < operation.minStack {
				res, err = nil, &ErrStackUnderflow{stackLen: stack.len(), required: operation.minStack}
				break mainLoop
			} else if stack.len() > operation.maxStack {
				res, err = nil, &ErrStackOverflow{stackLen: stack.len(), limit: operation.maxStack}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < operation.constantGas {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= operation.constantGas
			contract.Gas.UsedExecutionGas += operation.constantGas

			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = operation.execute(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		}
	}
	if err == errStopToken {
		err = nil
	}
	return res, err
}
