// Code generated by core/vm/gen; DO NOT EDIT.

package vm

// execUntraced is the generated, tracing-free interpreter fast path. It is a
// switch over the opcode byte, which Go lowers to a jump table, replacing the
// legacy loop's indirect call through the per-fork JumpTable.
//
// Hot, fork-stable opcodes get their own case, with static gas and stack bounds
// emitted as constants and the handler called by name. Everything fork-varying
// is dispatched through the active per-fork table in the default case, so its
// volatile gas logic stays shared. EVM.Run selects this path when no tracer is
// configured.
//
// The handlers are called, not inlined here. Go's normal inline budget is far
// below the cost of these bodies, so getting them into the loop depends on a
// PGO profile marking them hot, which raises the budget to 2000. Build without
// a profile and this is a switch of calls, which is still cheaper than the
// legacy indirect call but gives up the inlining.
func (evm *EVM) execUntraced(scope *ScopeContext) (ret []byte, err error) {
	var (
		contract = scope.Contract
		mem      = scope.Memory
		stack    = scope.Stack
		table    = evm.table
		rules    = evm.chainRules
		pc       = uint64(0)
		res      []byte
	)
	// Which of these the switch uses depends on the tier assignments, so
	// keep them all live rather than tracking usage while emitting.
	_, _, _ = mem, rules, table
	// sp shadows the stack depth for the bounds checks. Each case steps it
	// by its opcode's known delta, and the table case re-reads it because
	// its delta is not known until run time.
	sp := stack.len()
mainLoop:
	for {
		op := contract.GetOp(pc)
		switch op {
		case ADD:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opAdd(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case MUL:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(5) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opMul(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case SUB:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opSub(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case DIV:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(5) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opDiv(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case ADDMOD:
			if sp < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 3}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(8) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opAddmod(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 2
			pc++
			continue mainLoop
		case MULMOD:
			if sp < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 3}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(8) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opMulmod(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 2
			pc++
			continue mainLoop
		case SIGNEXTEND:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(5) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opSignExtend(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case LT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opLt(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case GT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opGt(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case SLT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opSlt(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case SGT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opSgt(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case EQ:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opEq(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case ISZERO:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opIszero(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case AND:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opAnd(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case OR:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opOr(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case XOR:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opXor(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case NOT:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opNot(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case SHL:
			if rules.IsConstantinople {
				if sp < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
					break mainLoop
				}
				if !contract.Gas.ChargeExecutionOnly(3) {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				res, err = opSHL(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				sp -= 1
				pc++
				continue mainLoop
			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SHR:
			if rules.IsConstantinople {
				if sp < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
					break mainLoop
				}
				if !contract.Gas.ChargeExecutionOnly(3) {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				res, err = opSHR(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				sp -= 1
				pc++
				continue mainLoop
			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SAR:
			if rules.IsConstantinople {
				if sp < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
					break mainLoop
				}
				if !contract.Gas.ChargeExecutionOnly(3) {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				res, err = opSAR(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				sp -= 1
				pc++
				continue mainLoop
			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case KECCAK256:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(30) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			operation := table[op]
			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opKeccak256(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case CALLDATALOAD:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opCallDataLoad(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case POP:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(2) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPop(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case MLOAD:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			operation := table[op]
			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMload(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			operation := table[op]
			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 2
			pc++
			continue mainLoop
		case JUMP:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(8) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opJump(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 1
			pc++
			continue mainLoop
		case JUMPI:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(10) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opJumpi(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 2
			pc++
			continue mainLoop
		case JUMPDEST:
			if !contract.Gas.ChargeExecutionOnly(1) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opJumpdest(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case PUSH0:
			if rules.IsShanghai {
				if sp > 1023 {
					res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
					break mainLoop
				}
				if !contract.Gas.ChargeExecutionOnly(2) {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				res, err = opPush0(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				sp += 1
				pc++
				continue mainLoop
			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case PUSH1:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush1(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH2:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush2(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH3:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush3(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH4:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush4(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH8:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush8(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH16:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush16(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH20:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush20(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case PUSH32:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			res, err = opPush32(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp += 1
			pc++
			continue mainLoop
		case DUP1, DUP2, DUP3, DUP4, DUP5, DUP6, DUP7, DUP8, DUP9, DUP10, DUP11, DUP12, DUP13, DUP14, DUP15, DUP16:
			n := int(op-DUP1) + 1
			if sp < n {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: n}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			stack.dup(n)
			sp += 1
			pc++
			continue mainLoop
		case SWAP1, SWAP2, SWAP3, SWAP4, SWAP5, SWAP6, SWAP7, SWAP8, SWAP9, SWAP10, SWAP11, SWAP12, SWAP13, SWAP14, SWAP15, SWAP16:
			n := int(op-SWAP1) + 1
			if sp < n+1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: n + 1}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(3) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			stack.swap(n)
			pc++
			continue mainLoop
		case RETURN:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			operation := table[op]
			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opReturn(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp -= 2
			pc++
			continue mainLoop
		default:
			operation := table[op]
			if sp < operation.minStack {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: operation.minStack}
				break mainLoop
			} else if sp > operation.maxStack {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: operation.maxStack}
				break mainLoop
			}
			if !contract.Gas.ChargeExecutionOnly(operation.constantGas) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = operation.execute(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			sp = stack.len()
			pc++
			continue mainLoop
		}
	}
	if err == errStopToken {
		err = nil
	}
	return res, err
}
