// Code generated by core/vm/gen; DO NOT EDIT.

package vm

import (
	"fmt"

	"github.com/ethereum/go-ethereum/common/math"
	"github.com/ethereum/go-ethereum/core/tracing"
)

// execUntraced is the generated, tracing-free interpreter fast path. Hot,
// fork-stable opcodes are inlined with their static gas and stack bounds emitted
// as constants. Fork-invariant ops (KECCAK256/MLOAD/MSTORE/MSTORE8) call their
// handler and gas functions directly by name. Everything fork-varying is
// dispatched through the active per-fork table in the default case. EVM.Run
// selects this path when no tracer is configured.
func (evm *EVM) execUntraced(scope *ScopeContext) (ret []byte, err error) {
	var (
		contract  = scope.Contract
		mem       = scope.Memory
		stack     = scope.Stack
		table     = evm.table
		rules     = evm.chainRules
		isEIP4762 = rules.IsEIP4762
		pc        = uint64(0)
		res       []byte
	)
	// Which of these the switch uses depends on the tier assignments, so
	// keep them all live rather than tracking usage while emitting.
	_, _, _, _ = mem, rules, isEIP4762, table
	// sp and sd shadow stack.size and the stack's window of the arena
	// as loop locals, so hot opcodes work on registers instead of the
	// view. They are written back before any call that can see the
	// stack and reloaded after any call that can move it.
	sp := stack.size
	sd := stack.inner.data[stack.bottom:]
mainLoop:
	for {
		if isEIP4762 && !contract.IsDeployment && !contract.IsSystemCall {
			contractAddr := contract.Address()
			consumed, wanted := evm.TxContext.AccessEvents.CodeChunksRangeGas(contractAddr, pc, 1, uint64(len(contract.Code)), false, contract.Gas.ExecutionGas)
			contract.chargeExecution(consumed, evm.Config.Tracer, tracing.GasChangeWitnessCodeChunk)
			if consumed < wanted {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
		}

		op := contract.GetOp(pc)
		switch op {
		case ADD:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Add(x, y)
			pc++
			continue mainLoop

		case MUL:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Mul(x, y)
			pc++
			continue mainLoop

		case SUB:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Sub(x, y)
			pc++
			continue mainLoop

		case DIV:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Div(x, y)
			pc++
			continue mainLoop

		case SDIV:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.SDiv(x, y)
			pc++
			continue mainLoop

		case MOD:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Mod(x, y)
			pc++
			continue mainLoop

		case SMOD:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.SMod(x, y)
			pc++
			continue mainLoop

		case ADDMOD:
			if sp < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 3}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 8 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 8

			sp -= 2
			x := &sd[sp+1]
			y := &sd[sp]
			z := &sd[sp-1]
			z.AddMod(x, y, z)
			pc++
			continue mainLoop

		case MULMOD:
			if sp < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 3}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 8 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 8

			sp -= 2
			x := &sd[sp+1]
			y := &sd[sp]
			z := &sd[sp-1]
			z.MulMod(x, y, z)
			pc++
			continue mainLoop

		case SIGNEXTEND:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 5 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 5

			sp--
			back := &sd[sp]
			num := &sd[sp-1]
			num.ExtendSign(num, back)
			pc++
			continue mainLoop

		case LT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			if x.Lt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case GT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			if x.Gt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case SLT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			if x.Slt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case SGT:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			if x.Sgt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case EQ:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			if x.Eq(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case ISZERO:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			x := &sd[sp-1]
			if x.IsZero() {
				x.SetOne()
			} else {
				x.Clear()
			}
			pc++
			continue mainLoop

		case AND:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.And(x, y)
			pc++
			continue mainLoop

		case OR:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Or(x, y)
			pc++
			continue mainLoop

		case XOR:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			x := &sd[sp]
			y := &sd[sp-1]
			y.Xor(x, y)
			pc++
			continue mainLoop

		case NOT:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			x := &sd[sp-1]
			x.Not(x)
			pc++
			continue mainLoop

		case BYTE:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sp--
			th := &sd[sp]
			val := &sd[sp-1]
			val.Byte(th)
			pc++
			continue mainLoop

		case SHL:
			if rules.IsConstantinople {
				if sp < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 3 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 3

				sp--
				shift := &sd[sp]
				value := &sd[sp-1]
				if shift.LtUint64(256) {
					value.Lsh(value, uint(shift.Uint64()))
				} else {
					value.Clear()
				}
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SHR:
			if rules.IsConstantinople {
				if sp < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 3 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 3

				sp--
				shift := &sd[sp]
				value := &sd[sp-1]
				if shift.LtUint64(256) {
					value.Rsh(value, uint(shift.Uint64()))
				} else {
					value.Clear()
				}
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SAR:
			if rules.IsConstantinople {
				if sp < 2 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 3 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 3

				sp--
				shift := &sd[sp]
				value := &sd[sp-1]
				if shift.GtUint64(256) {
					if value.Sign() >= 0 {
						value.Clear()
					} else {

						value.SetAllOne()
					}
					pc++
					continue mainLoop
				}
				n := uint(shift.Uint64())
				value.SRsh(value, n)
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case CLZ:
			if rules.IsOsaka {
				if sp < 1 {
					res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 5 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 5

				x := &sd[sp-1]
				x.SetUint64(256 - uint64(x.BitLen()))
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case KECCAK256:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 30 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 30

			stack.size = sp
			stack.inner.top = stack.bottom + sp
			var memorySize uint64
			memSize, overflow := memoryKeccak256(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := gasKeccak256(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opKeccak256(&pc, evm, scope)
			sp = stack.size
			sd = stack.inner.data[stack.bottom:]
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case POP:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 2 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 2

			sp--
			pc++
			continue mainLoop

		case MLOAD:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			stack.size = sp
			stack.inner.top = stack.bottom + sp
			var memorySize uint64
			memSize, overflow := memoryMLoad(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := pureMemoryGascost(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMload(&pc, evm, scope)
			sp = stack.size
			sd = stack.inner.data[stack.bottom:]
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			stack.size = sp
			stack.inner.top = stack.bottom + sp
			var memorySize uint64
			memSize, overflow := memoryMStore(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := pureMemoryGascost(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore(&pc, evm, scope)
			sp = stack.size
			sd = stack.inner.data[stack.bottom:]
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE8:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			stack.size = sp
			stack.inner.top = stack.bottom + sp
			var memorySize uint64
			memSize, overflow := memoryMStore8(stack)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			size, overflow := math.SafeMul(toWordSize(memSize), 32)
			if overflow {
				res, err = nil, ErrGasUintOverflow
				break mainLoop
			}
			memorySize = size

			dynamicCost, gerr := pureMemoryGascost(evm, contract, stack, mem, memorySize)
			if gerr != nil {
				res, err = nil, fmt.Errorf("%w: %v", ErrOutOfGas, gerr)
				break mainLoop
			}
			if dynamicCost.StateGas == 0 {
				if cerr := contract.Gas.ChargeExecutionOnly(dynamicCost.ExecutionGas); cerr != nil {
					res, err = nil, cerr
					break mainLoop
				}
			} else if !contract.Gas.charge(dynamicCost) {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}

			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore8(&pc, evm, scope)
			sp = stack.size
			sd = stack.inner.data[stack.bottom:]
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case JUMP:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 8 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 8

			if evm.abort.Load() {
				res, err = nil, errStopToken
				break mainLoop
			}
			sp--
			pos := &sd[sp]
			if !contract.validJumpdest(pos) {
				res, err = nil, ErrInvalidJump
				break mainLoop
			}
			pc = pos.Uint64() - 1
			pc++
			continue mainLoop

		case JUMPI:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 10 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 10

			if evm.abort.Load() {
				res, err = nil, errStopToken
				break mainLoop
			}
			sp -= 2
			pos := &sd[sp+1]
			cond := &sd[sp]
			if !cond.IsZero() {
				if !contract.validJumpdest(pos) {
					res, err = nil, ErrInvalidJump
					break mainLoop
				}
				pc = pos.Uint64() - 1
			}
			pc++
			continue mainLoop

		case PC:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 2 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 2

			elem := &sd[sp]
			sp++
			elem.SetUint64(pc)
			pc++
			continue mainLoop

		case MSIZE:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 2 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 2

			elem := &sd[sp]
			sp++
			elem.SetUint64(uint64(scope.Memory.Len()))
			pc++
			continue mainLoop

		case JUMPDEST:
			if contract.Gas.ExecutionGas < 1 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 1

			pc++
			continue mainLoop

		case PUSH0:
			if rules.IsShanghai {
				if sp > 1023 {
					res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
					break mainLoop
				}
				if contract.Gas.ExecutionGas < 2 {
					res, err = nil, ErrOutOfGas
					break mainLoop
				}
				contract.Gas.ExecutionGas -= 2

				elem := &sd[sp]
				sp++
				elem.Clear()
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case PUSH1:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			codeLen := uint64(len(contract.Code))
			elem := &sd[sp]
			sp++
			pc += 1
			if pc < codeLen {
				elem.SetUint64(uint64(contract.Code[pc]))
			} else {
				elem.Clear()
			}
			pc++
			continue mainLoop

		case PUSH2:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			codeLen := uint64(len(contract.Code))
			elem := &sd[sp]
			sp++
			if pc+2 < codeLen {
				elem.SetBytes2(contract.Code[pc+1 : pc+3])
			} else if pc+1 < codeLen {
				elem.SetUint64(uint64(contract.Code[pc+1]) << 8)
			} else {
				elem.Clear()
			}
			pc += 2
			pc++
			continue mainLoop

		case PUSH3:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+3 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes3(contract.Code[p : p+3])
				pc += 3
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+3)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 3 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 3
			pc++
			continue mainLoop

		case PUSH4:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+4 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes4(contract.Code[p : p+4])
				pc += 4
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+4)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 4 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 4
			pc++
			continue mainLoop

		case PUSH5:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+5 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes5(contract.Code[p : p+5])
				pc += 5
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+5)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 5 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 5
			pc++
			continue mainLoop

		case PUSH6:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+6 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes6(contract.Code[p : p+6])
				pc += 6
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+6)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 6 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 6
			pc++
			continue mainLoop

		case PUSH7:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+7 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes7(contract.Code[p : p+7])
				pc += 7
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+7)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 7 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 7
			pc++
			continue mainLoop

		case PUSH8:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+8 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes8(contract.Code[p : p+8])
				pc += 8
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+8)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 8 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 8
			pc++
			continue mainLoop

		case PUSH9:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+9 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes9(contract.Code[p : p+9])
				pc += 9
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+9)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 9 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 9
			pc++
			continue mainLoop

		case PUSH10:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+10 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes10(contract.Code[p : p+10])
				pc += 10
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+10)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 10 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 10
			pc++
			continue mainLoop

		case PUSH11:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+11 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes11(contract.Code[p : p+11])
				pc += 11
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+11)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 11 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 11
			pc++
			continue mainLoop

		case PUSH12:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+12 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes12(contract.Code[p : p+12])
				pc += 12
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+12)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 12 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 12
			pc++
			continue mainLoop

		case PUSH13:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+13 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes13(contract.Code[p : p+13])
				pc += 13
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+13)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 13 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 13
			pc++
			continue mainLoop

		case PUSH14:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+14 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes14(contract.Code[p : p+14])
				pc += 14
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+14)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 14 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 14
			pc++
			continue mainLoop

		case PUSH15:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+15 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes15(contract.Code[p : p+15])
				pc += 15
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+15)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 15 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 15
			pc++
			continue mainLoop

		case PUSH16:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+16 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes16(contract.Code[p : p+16])
				pc += 16
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+16)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 16 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 16
			pc++
			continue mainLoop

		case PUSH17:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+17 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes17(contract.Code[p : p+17])
				pc += 17
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+17)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 17 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 17
			pc++
			continue mainLoop

		case PUSH18:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+18 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes18(contract.Code[p : p+18])
				pc += 18
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+18)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 18 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 18
			pc++
			continue mainLoop

		case PUSH19:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+19 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes19(contract.Code[p : p+19])
				pc += 19
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+19)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 19 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 19
			pc++
			continue mainLoop

		case PUSH20:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+20 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes20(contract.Code[p : p+20])
				pc += 20
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+20)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 20 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 20
			pc++
			continue mainLoop

		case PUSH21:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+21 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes21(contract.Code[p : p+21])
				pc += 21
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+21)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 21 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 21
			pc++
			continue mainLoop

		case PUSH22:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+22 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes22(contract.Code[p : p+22])
				pc += 22
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+22)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 22 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 22
			pc++
			continue mainLoop

		case PUSH23:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+23 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes23(contract.Code[p : p+23])
				pc += 23
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+23)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 23 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 23
			pc++
			continue mainLoop

		case PUSH24:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+24 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes24(contract.Code[p : p+24])
				pc += 24
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+24)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 24 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 24
			pc++
			continue mainLoop

		case PUSH25:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+25 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes25(contract.Code[p : p+25])
				pc += 25
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+25)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 25 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 25
			pc++
			continue mainLoop

		case PUSH26:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+26 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes26(contract.Code[p : p+26])
				pc += 26
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+26)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 26 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 26
			pc++
			continue mainLoop

		case PUSH27:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+27 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes27(contract.Code[p : p+27])
				pc += 27
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+27)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 27 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 27
			pc++
			continue mainLoop

		case PUSH28:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+28 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes28(contract.Code[p : p+28])
				pc += 28
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+28)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 28 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 28
			pc++
			continue mainLoop

		case PUSH29:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+29 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes29(contract.Code[p : p+29])
				pc += 29
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+29)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 29 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 29
			pc++
			continue mainLoop

		case PUSH30:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+30 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes30(contract.Code[p : p+30])
				pc += 30
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+30)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 30 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 30
			pc++
			continue mainLoop

		case PUSH31:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+31 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes31(contract.Code[p : p+31])
				pc += 31
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+31)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 31 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 31
			pc++
			continue mainLoop

		case PUSH32:
			if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			if isEIP4762 {
				stack.size = sp
				stack.inner.top = stack.bottom + sp
				res, err = table[op].execute(&pc, evm, scope)
				sp = stack.size
				sd = stack.inner.data[stack.bottom:]
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			if p := int(pc + 1); p+32 <= len(contract.Code) {
				a := &sd[sp]
				sp++
				a.SetBytes32(contract.Code[p : p+32])
				pc += 32
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+32)
			)
			a := &sd[sp]
			sp++
			a.SetBytes(contract.Code[start:end])
			if missing := 32 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 32
			pc++
			continue mainLoop

		case DUP1:
			if sp < 1 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 1}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-1]
			sp++
			pc++
			continue mainLoop

		case DUP2:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-2]
			sp++
			pc++
			continue mainLoop

		case DUP3:
			if sp < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 3}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-3]
			sp++
			pc++
			continue mainLoop

		case DUP4:
			if sp < 4 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 4}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-4]
			sp++
			pc++
			continue mainLoop

		case DUP5:
			if sp < 5 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 5}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-5]
			sp++
			pc++
			continue mainLoop

		case DUP6:
			if sp < 6 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 6}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-6]
			sp++
			pc++
			continue mainLoop

		case DUP7:
			if sp < 7 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 7}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-7]
			sp++
			pc++
			continue mainLoop

		case DUP8:
			if sp < 8 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 8}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-8]
			sp++
			pc++
			continue mainLoop

		case DUP9:
			if sp < 9 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 9}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-9]
			sp++
			pc++
			continue mainLoop

		case DUP10:
			if sp < 10 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 10}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-10]
			sp++
			pc++
			continue mainLoop

		case DUP11:
			if sp < 11 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 11}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-11]
			sp++
			pc++
			continue mainLoop

		case DUP12:
			if sp < 12 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 12}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-12]
			sp++
			pc++
			continue mainLoop

		case DUP13:
			if sp < 13 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 13}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-13]
			sp++
			pc++
			continue mainLoop

		case DUP14:
			if sp < 14 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 14}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-14]
			sp++
			pc++
			continue mainLoop

		case DUP15:
			if sp < 15 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 15}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-15]
			sp++
			pc++
			continue mainLoop

		case DUP16:
			if sp < 16 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 16}
				break mainLoop
			} else if sp > 1023 {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: 1023}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp] = sd[sp-16]
			sp++
			pc++
			continue mainLoop

		case SWAP1:
			if sp < 2 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 2}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-2], sd[sp-1] = sd[sp-1], sd[sp-2]
			pc++
			continue mainLoop

		case SWAP2:
			if sp < 3 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 3}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-3], sd[sp-1] = sd[sp-1], sd[sp-3]
			pc++
			continue mainLoop

		case SWAP3:
			if sp < 4 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 4}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-4], sd[sp-1] = sd[sp-1], sd[sp-4]
			pc++
			continue mainLoop

		case SWAP4:
			if sp < 5 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 5}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-5], sd[sp-1] = sd[sp-1], sd[sp-5]
			pc++
			continue mainLoop

		case SWAP5:
			if sp < 6 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 6}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-6], sd[sp-1] = sd[sp-1], sd[sp-6]
			pc++
			continue mainLoop

		case SWAP6:
			if sp < 7 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 7}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-7], sd[sp-1] = sd[sp-1], sd[sp-7]
			pc++
			continue mainLoop

		case SWAP7:
			if sp < 8 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 8}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-8], sd[sp-1] = sd[sp-1], sd[sp-8]
			pc++
			continue mainLoop

		case SWAP8:
			if sp < 9 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 9}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-9], sd[sp-1] = sd[sp-1], sd[sp-9]
			pc++
			continue mainLoop

		case SWAP9:
			if sp < 10 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 10}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-10], sd[sp-1] = sd[sp-1], sd[sp-10]
			pc++
			continue mainLoop

		case SWAP10:
			if sp < 11 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 11}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-11], sd[sp-1] = sd[sp-1], sd[sp-11]
			pc++
			continue mainLoop

		case SWAP11:
			if sp < 12 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 12}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-12], sd[sp-1] = sd[sp-1], sd[sp-12]
			pc++
			continue mainLoop

		case SWAP12:
			if sp < 13 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 13}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-13], sd[sp-1] = sd[sp-1], sd[sp-13]
			pc++
			continue mainLoop

		case SWAP13:
			if sp < 14 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 14}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-14], sd[sp-1] = sd[sp-1], sd[sp-14]
			pc++
			continue mainLoop

		case SWAP14:
			if sp < 15 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 15}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-15], sd[sp-1] = sd[sp-1], sd[sp-15]
			pc++
			continue mainLoop

		case SWAP15:
			if sp < 16 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 16}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-16], sd[sp-1] = sd[sp-1], sd[sp-16]
			pc++
			continue mainLoop

		case SWAP16:
			if sp < 17 {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: 17}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < 3 {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= 3

			sd[sp-17], sd[sp-1] = sd[sp-1], sd[sp-17]
			pc++
			continue mainLoop

		default:
			operation := table[op]
			if sp < operation.minStack {
				res, err = nil, &ErrStackUnderflow{stackLen: sp, required: operation.minStack}
				break mainLoop
			} else if sp > operation.maxStack {
				res, err = nil, &ErrStackOverflow{stackLen: sp, limit: operation.maxStack}
				break mainLoop
			}
			if contract.Gas.ExecutionGas < operation.constantGas {
				res, err = nil, ErrOutOfGas
				break mainLoop
			}
			contract.Gas.ExecutionGas -= operation.constantGas

			stack.size = sp
			stack.inner.top = stack.bottom + sp
			var memorySize uint64
			if memorySize, _, err = contract.meterDynamicGas(operation, evm, stack, mem); err != nil {
				return nil, err
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = operation.execute(&pc, evm, scope)
			sp = stack.size
			sd = stack.inner.data[stack.bottom:]
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		}
	}
	stack.size = sp
	stack.inner.top = stack.bottom + sp
	if err == errStopToken {
		err = nil
	}
	return res, err
}
